### ISSUE TITLE
How would one get the hightlights for projects back?

### ISSUE THREAD

**Issue by gromanmartin** [floriankammermann/landscapeapp#2]
Hi, I am still playing around with your fork and I am trying to figure out how to get the highlight for items in the landscape, that belong to specific project, basically the original feature. I know nothing about JS, but I have managed to track back and restore images instead of text in my fork, however I am unable to make the project highlights work. Do you have any hints, where to look at or what to edit?
Cheers, M.

**Comment by floriankammermann** [comment]
I can not classify "highlight". From my understanding is one item is one project. What is highlight in this context, a visual effect?
Probably a picture would help to explain.

**Comment by gromanmartin** [comment]
I should have been more specific. If you take a look at this landscape for example https://landscape.cd.foundation/. In the first category - CI and pipeline orchestration, you can see 4 projects - JenkinsX, Screwdriver CD, Spinnaker, Tekton. They have blue border as opposed to small items like agola, gitlab and others. I think in the code they are named LargeItems. So I am trying to get the blue border and make certain items bigger.  
I guess it is not really relevant for your fork, since you removed the pictures altogether, so I was just wondering if you happen to know, how to get this functionality back.
Thank you for your time.

**Comment by floriankammermann** [comment]
I fixed it and was able to render BigItems, when I added the following line in the landscape.yml: `project: graduated`

**Comment by gromanmartin** [comment]
Thank you, it works perfectly.
